version: '3'

services:
  nestapp:
    container_name: nestapp
    image: nestapp:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
  database:
    image: 'mongo'
    container_name: 'mongo'
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-volume:/data/db
    ports:
      - '27017:27017'